### ISSUE TITLE
Thank you for your work! problem with the results

### ISSUE THREAD

**Issue by tommasogattari** [kathyliu579/CS-Unet#2]
Hello, thank you for the work you have done and for making it available for study. I would like to ask you, how do you get a result like the one you see in the first figure of your sheet? Personally I expected, after testing, that in the images there were 9 segmentation maps and instead it is not so. So my doubt is that I'm wrong or is there a way to display the results that I don't know. Can someone help me?

![image](https://user-images.githubusercontent.com/48884211/232878937-f8ffee09-4d5f-40fe-a7c5-86e732026739.png)

**Comment by kathyliu579** [comment]
Hi here, sorry to reply late. 
Yes, the dataset has 9 classes, but sometimes a slice of image only has fewer classes. You use can generate mask figure and then add them on ture image(grey one ). Then you can get our visiualization. 
Thanks very much for your attention!
