### ISSUE TITLE
problem with AdamW optimizer

### ISSUE THREAD

**Issue by tommasogattari** [kathyliu579/CS-Unet#3]
Using this optmizier i always encounter the same problem:
Epoch 0 - train: 100%|████████████████████████████████████████████| 1/1 [00:13<00:00, 13.35s/it, loss=1.46, lr=0.00719]
Epoch 1 - train: 100%|█████████████████████████████████████████████| 1/1 [00:15<00:00, 15.85s/it, loss=1.44, lr=0.0143]
Epoch 2 - train: 100%|█████████████████████████████████████████████| 1/1 [00:15<00:00, 15.54s/it, loss=1.07, lr=0.0215]
Epoch 3 - train: 100%|████████████████████████████████████████████| 1/1 [00:18<00:00, 18.09s/it, loss=0.508, lr=0.0286]
Epoch 4 - train: 100%|█████████████████████████████████████████████| 1/1 [00:15<00:00, 15.87s/it, loss=88.8, lr=0.0357]
Epoch 5 - train: 100%|█████████████████████████████████████████████| 1/1 [00:34<00:00, 34.69s/it, loss=10.8, lr=0.0429]
Epoch 6 - train: 100%|███████████████████████████████████████████████| 1/1 [00:42<00:00, 42.98s/it, loss=6.61, lr=0.05]
Epoch 7 - train:   0%|                                                                           | 0/1 [00:00<?, ?it/s]NaN or Inf found in input tensor.
NaN or Inf found in input tensor.
Epoch 7 - train: 100%|██████████████████████████████████████████████| 1/1 [00:16<00:00, 16.58s/it, loss=nan, lr=0.0497]
Epoch 8 - train:   0%|                                                                           | 0/1 [00:00<?, ?it/s]NaN or Inf found in input tensor.
NaN or Inf found in input tensor.
Epoch 8 - train: 100%|██████████████████████████████████████████████| 1/1 [00:15<00:00, 15.72s/it, loss=nan, lr=0.0494]
Epoch 9 - train:   0%|                                                                           | 0/1 [00:00<?, ?it/s]NaN or Inf found in input tensor.
NaN or Inf found in input tensor.

Meanwhile, using SGD this problem doesn't appear. Can you help me?

**Comment by kathyliu579** [comment]
Hi it is a little werid, as our code is based Adamw without problem.
